const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

module.exports = { FETCH_USER_REQUEST, FETCH_USER_SUCCESS, FETCH_USER_FAIL };